#cloud-config

runcmd:
 - sleep 30
 - sudo yum update -y
 - cd /tmp
 - curl -ksLO https://d3pxv6yz143wms.cloudfront.net/java-1.8.0-amazon-corretto-1.8.0_192.b12-1.amzn2.x86_64.rpm
 - sudo yum install -y ./java-1.8.0-amazon-corretto-1.8.0_192.b12-1.amzn2.x86_64.rpm
 - sudo alternatives --set java /usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64/jre/bin/java
 - curl -ksLO ${nifi_url}
 - tar xzf nifi-1.8.0-bin.tar.gz
 - sudo mkdir -p /opt/nifi
 - mv nifi-1.8.0 /opt/nifi/
 - sudo chown -R centos /opt/nifi
 - rm nifi-1.8.0-bin.tar.gz
 - cd /opt/nifi/nifi-1.8.0
 - cd bin 
 - sudo ./nifi.sh install
 - ./nifi.sh start

